platform :ios, '12.1'
use_frameworks!

target 'JustAnApp' do
    # External setup
    pod "MultiSDK", :git => 'git@github.com:amichnia/optional-frameworks-tests.git'
    pod "MultiSDK/AdditionalSDK", :git => 'git@github.com:amichnia/optional-frameworks-tests.git'

    # Develpoment - local setup, uncomment for tests only
    # pod "MultiSDK", :path => './..'
    # pod "MultiSDK/AdditionalSDK", :path => './..'
end
